version: "3.7"

volumes:
  pg-data:
    name: pg-data

networks:
  db-network:
    name: db-network

services:
  postgres:
    image: postgres:12.0
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d/
    networks:
      - db-network
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    networks:
      - db-network
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]